version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  assignees:
  - idoneam/dependabot-assignees
  labels:
  - dependencies
