[tool.poetry]
name = "Canary"
version = "3.0.3"
description = ""
license = "GPL-3.0-only"
repository = "https://github.com/idoneam/Canary"
readme = "README.md"
authors = []

[tool.poetry.dependencies]
python = "^3.9.0"
beautifulsoup4 = "==4.10.0"
sympy = "^1.9"
requests = ">=2.20.0"
tabulate = "==0.8.9"
"discord.py" = "~1.6.0"
opencv-python = "==4.5.3.56"
pytz = ">=2020.5"
numpy = "^1.21.1"
aiohttp = "~3.7.4"
urllib3 = ">=1.25.3"
feedparser = "^6.0.8"
regex = "^2021.10.8"
googletrans = "==4.0.0rc1"
Pillow = "^8.4.0"

[tool.poetry.dev-dependencies]
yapf = "==0.31.0"
pytest = "^6.2.5"
