[tool.poetry]
name = "Canary"
version = "4.0.1"
description = ""
license = "GPL-3.0-only"
repository = "https://github.com/idoneam/Canary"
readme = "README.md"
authors = []
packages = [
  { include = "canary" },
]
include = [
    "canary/Martlet.schema",
]

[tool.poetry.scripts]
canary = "canary.main:main"

[tool.poetry.dependencies]
python = ">=3.10.0,<3.12"
beautifulsoup4 = "^4.12.3"
sympy = "^1.13.2"
requests = ">=2.32.3,<3"
tabulate = "~0.9.0"
"discord.py" = {version = "~1.7.3", extras = ["voice"]}
opencv-python = "==4.10.0.84"
pytz = ">=2024.1"
numpy = "^1.26.4"
aiohttp = "~3.7.4.post0"
urllib3 = "~2.0.7"
feedparser = "^6.0.8"
regex = "^2024.7.24"
googletrans = "==4.0.0rc1"
yt-dlp = "^2024.4.9"
Pillow = "^9.5.0"
uvloop = {version="~0.20.0", markers = "sys_platform == 'linux' or sys_platform == 'darwin'"}
bidict = "^0.22.0"
aiosqlite = "^0.19.0"
lxml = "^4.9.1"
python-dotenv = "^0.21.0"
pydantic = "^2.9.2"

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"
black = "^24.8.0"
mypy = "~1.11.2"
types-beautifulsoup4 = "^4.12.0.20240511"
types-regex = "^2024.7.24.20240726"
types-requests = "^2.32.0.20240712"
types-pytz = "^2024.1.0.20240417"
types-tabulate = "^0.8.11"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
