[tool.poetry]
name = "Canary"
version = "2.1.0"
description = ""
license = "GPL-3.0-only"
repository = "https://github.com/idoneam/Canary"
readme = "README.md"
authors = []

[tool.poetry.dependencies]
python = "^3.9.0"
beautifulsoup4 = "==4.9.3"
sympy = "==1.7.1"
requests = ">=2.20.0"
tabulate = "==0.8.9"
"discord.py" = "~1.6.0"
opencv-python = "==4.5.1.48"
pytz = ">=2020.5"
numpy = "^1.20.2"
aiohttp = "~3.7.4"
urllib3 = ">=1.25.3"
feedparser = "^6.0.2"
regex = "^2021.3.17"
googletrans = "==4.0.0rc1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
black = "^20.8b1"

[tool.black]
line-length = 120