name: Prod Dependencies
on:
  pull_request:
    branches:
      - 'dev'
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/poetry*.yml'

jobs:
  poetry-prod-build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os:
          - 'ubuntu-20.04'
          - 'ubuntu-18.04'
        python-version:
          - '3.10'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Get Poetry version
        run: poetry --version

      - name: Check pyproject.toml validity
        run: poetry check --no-interaction

      - name: install canary production dependencies
        run: poetry install --no-dev --no-interaction

