name: Dev Dependencies
on:
  push:
    branches:
      - dev
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/poetry*.yml'
  pull_request:
    branches:
      - dev
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/poetry*.yml'

jobs:
  poetry-dev-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-20.04'
          - 'ubuntu-18.04'
          # - 'macos-10.15'
          - 'macos-11.0'
          - 'windows-latest'
        python-version:
          - '3.10'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install latest version of Poetry for Windows
        if: matrix.os == 'windows-latest'
        run: (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
      - name: Install latest version of Poetry
        if: matrix.os != 'windows-latest'
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Add Poetry to PATH on Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "%USERPROFILE%\AppData\Roaming\Python\scripts\poetry" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell
      - name: Add Poetry to PATH
        if: matrix.os != 'windows-latest'
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Get Poetry version
        run: poetry --version

      - name: Check pyproject.toml validity
        run: poetry check --no-interaction

      - name: install canary development dependencies
        run: poetry install --no-interaction

