name: Prod Dependencies
on:
  pull_request:
    branches:
      - 'dev'
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/poetry*.yml'

jobs:
  poetry-prod-build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os:
          - 'ubuntu-20.04'
          - 'ubuntu-18.04'
        python-version:
          - '3.10'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install --upgrade poetry pip setuptools wheel

      - name: Get Poetry version
        run: poetry --version

      - name: Check pyproject.toml validity
        run: poetry check --no-interaction

      - name: install canary production dependencies (macos)
        if: matrix.os == 'macos-11.0'
        run: curl https://files.pythonhosted.org/packages/fe/0a/96e00caf7a4d9ce79c8eeac1ae3880833e11913e5719a85b259103bcb1c6/opencv_python-4.5.4.60-cp310-cp310-macosx_11_0_x86_64.whl > opencv_python-4.5.4.60-cp310-cp310-macosx_10_16_x86_64.whl && poetry run pip install opencv_python-4.5.4.60-cp310-cp310-macosx_10_16_x86_64.whl && poetry install --no-dev --no-interaction

      - name: install canary production dependencies (non macos)
        if: matrix.os != 'macos-11.0'
        run: poetry install --no-dev --no-interaction

